Rectangular angle profile and compilation bug fix
dbeurle/neon pull request #138
Opened 2018-12-27 20:50 UTC by annierhea

This PR includes the addition of rectangular angle geometry profiles and testing.  Further geometry profiles and documentation are still needed before this section is complete.

As a side patch, the `ENABLE_OPENCL` preprocessor symbol was added around ViennaCL for the eigenvalue solvers in order to fix a compilation bug caused when a machine has no ViennaCL installation and has not enabled the `ENABLE_OPENCL` option, as discovered by using a different machine for compilation.

2018-12-27 21:16 UTC, dbeurle requested changes

2018-12-27 21:16 UTC, dbeurle commented on src/solver/eigen/eigen_solver_factory.cpp
> +#ifndef ENABLE_OPENCL
These would need to specify what option requires OPENCL support (i.e. The "lanczos" option...).

2018-12-28 17:05 UTC, annierhea commented on src/geometry/profile.hpp
>  };
Done.

2018-12-28 17:05 UTC, annierhea commented on test/geometry_profile.cpp
> +    }
Done.

2018-12-28 17:07 UTC, dbeurle approved these changes

2018-12-28 20:40 UTC, merged